"""Tier 2 ML score models and suggestion retrieval index.

This package contains:
  - scorer_*.py     Pure Python score models (generated by m2cgen)
  - suggestion_index.pkl   kNN retrieval index for suggestions
  - shap_weights.json      Feature importance weights
  - feature_config.json    Feature names + normalization bounds

After training, copy artifacts from backend/ml/exported/ to this directory.
The models are loaded lazily on first use of compute_score_ml().
"""
from pathlib import Path

TIER2_DIR = Path(__file__).parent


def models_available() -> bool:
    """Check if Tier 2 quality model files are bundled."""
    return (
        (TIER2_DIR / "scorer_headline.py").exists()
        and (TIER2_DIR / "feature_config.json").exists()
    )


def safety_models_available() -> bool:
    """Check if Tier 2 safety model files are bundled."""
    feature_config = TIER2_DIR / "safety_feature_config.json"
    legacy_available = (TIER2_DIR / "scorer_safety.py").exists()
    ordinal_available = all(
        (TIER2_DIR / f"scorer_safety_lt{cut}.py").exists()
        for cut in (30, 60, 80)
    )
    return feature_config.exists() and (legacy_available or ordinal_available)
