"""Tier 2 ML score models and suggestion retrieval index.

This package contains:
  - scorer_*.py     Pure Python score models (generated by m2cgen)
  - suggestion_index.pkl   kNN retrieval index for suggestions
  - shap_weights.json      Feature importance weights
  - feature_config.json    Feature names + normalization bounds

After training, copy artifacts from backend/ml/exported/ to this directory.
The models are loaded lazily on first use of compute_score_ml().
"""
from pathlib import Path

TIER2_DIR = Path(__file__).parent


def models_available() -> bool:
    """Check if Tier 2 model files are bundled."""
    return (
        (TIER2_DIR / "scorer_headline.py").exists()
        and (TIER2_DIR / "feature_config.json").exists()
    )
